language: android
android:
  components:
    # The BuildTools version used by the project
    - build-tools-25.0.0

    # The SDK version used to compile
    - android-19
    - sys-img-armeabi-v7a-android-19

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository # Google Play Services
    # - extra-android-m2repository # Design Support Library
    # - addon-google_apis-google-19