language: android
jdk: oraclejdk8
android:
  components:
    # The BuildTools version used by the project
    - build-tools-25.0.0

    # The SDK version used to compile
    - android-19
    - sys-img-armeabi-v7a-android-19

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository # Gradle 2.3.1
    - extra-android-m2repository
    # - addon-google_apis-google-19
before_install:
 - chmod +x gradlew # Fixes "./gradlew: Permission denied"
notifications:
  slack: iethfgroup:b4VDqxMEG6P243YziEaGda52